---
# tasks file for common
- name: install ufw
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: ufw already enabled
  command: ufw status verbose
  register: ufw_status_result
  changed_when: False

- name: open ssh port
  command: ufw allow 22/tcp
  when: not ufw_status_result.stdout is search("22/tcp.*ALLOW IN.*Anywhere")

- name: open node_exporter port
  command: ufw allow 9100/tcp
  when:
    - not ufw_status_result.stdout is search("9100/tcp.*ALLOW IN.*Anywhere")

- name: open p2p port
  command: ufw allow 30333/tcp
  when:
    - not ufw_status_result.stdout is search("30333/tcp.*ALLOW IN.*Anywhere")

- name: open RPC port
  command: ufw allow 9933/tcp
  when:
    - not ufw_status_result.stdout is search("9933/tcp.*ALLOW IN.*Anywhere")

- name: open health check port
  command: ufw allow 5500/tcp
  when:
    - not ufw_status_result.stdout is search("5500/tcp.*ALLOW IN.*Anywhere")

- name: enable firewall
  shell: |
    set -o pipefail
    echo "y" | ufw enable
  args:
    executable: /bin/bash
  when: not ufw_status_result.stdout is search("Status.* active")

- name: copy journald config
  copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
